### ISSUE TITLE
add style to delayed time (red/colored)

### ISSUE THREAD

**Issue by mdissel** [qistoph/MMM-nstreinen#14]
Maybe add some color to the rendered html with a red label for the delayed time.

**Comment by qistoph** [comment]
Sounds nice. Though I prefer my screen black&white. If you write a PR, please make it configurable.

Maybe something like "use_color": "boolean".

**Comment by qistoph** [comment]
Dear @mdissel,

If you update to the latest version you'll be able to change the styling from your custom.css:
```css
 .nstreinen .delayed .time {
     color: red;
 }
```
